[tool.poetry]
name = "brimo-sentiment"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.0.0"
pandas = "^2.2.2"
google-play-scraper = "^1.2.7"
requests = "^2.32.3"
twscrape = "^0.13"
playwright = "^1.45.0"
jmespath = "^1.0.1"
scrapfly-sdk = "^0.8.17"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
